name: Deploy Node.js Backend with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-backend:latest -f Shopee_Backend/Dockerfile ./Shopee_Backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Debug - List files in repo
          run:ls -R
      - name: Copy docker-compose.yml & database scripts to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: |
            docker-compose.yml
            Shopee_Backend/database
          target: "/home/${{ secrets.VPS_USER }}/projects/shopee-backend"

      - name: SSH into VPS and deploy (Project-Specific)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/projects/shopee-backend
            docker-compose down  # Dừng container cũ
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-backend:latest  # Kéo image BE mới nhất
            docker-compose up -d  # Chạy lại container
            docker system prune -af  # Dọn dẹp VPS, xóa image cũ
